#!/usr/bin/env csh
#
# Copyright (c) 2011 Michael Tuexen
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $Id: run-some-sua-sgp-tests,v 1.3 2011/03/20 16:53:06 tuexen Exp $
#

set timeout = 10
set testcases = (	sua-sgp-aspsm-v-01 \
			sua-sgp-aspsm-v-02 \
			sua-sgp-aspsm-v-03 \
			sua-sgp-aspsm-i-01 \
			sua-sgp-aspsm-i-02 \
			sua-sgp-aspsm-i-04 \
			sua-sgp-aspsm-o-01 \
			sua-sgp-aspsm-o-02 \
			sua-sgp-aspsm-o-03 \
			sua-sgp-asptm-v-01 \
			sua-sgp-asptm-v-02 \
			sua-sgp-asptm-v-04 \
			sua-sgp-asptm-v-05 \
			sua-sgp-asptm-v-06 \
			sua-sgp-asptm-v-07 \
			sua-sgp-asptm-i-01 \
			sua-sgp-asptm-i-03 \
			sua-sgp-asptm-i-04 \
			sua-sgp-asptm-i-05 \
			sua-sgp-asptm-i-06 \
			sua-sgp-asptm-i-08 \
			sua-sgp-asptm-o-01 \
			sua-sgp-asptm-o-02 \
			sua-sgp-mtr-i-01 \
			sua-sgp-mtr-i-02 \
			sua-sgp-mtr-i-03 \
			sua-sgp-mtr-i-04 \
		)

foreach testcase ($testcases)
  (run-sua-test -t $timeout $testcase > /dev/tty) >& /dev/null
end
