FROM debian:jessie

MAINTAINER Harald Welte <laforge@gnumonks.org>

RUN	apt-get update && apt-get install -y \
	build-essential \
	wget \
	git \
	make \
	autoconf \
	autogen \
	automake \
	libtool \
	pkg-config \
	libtalloc-dev \
	libpcsclite-dev \
	libortp-dev \
	libsctp-dev \
	libssl-dev \
	libdbi-dev \
	libdbd-sqlite3 \
	libsqlite3-dev \
	libpcap-dev \
	libc-ares-dev \
	sqlite3
