FROM debian:jessie

MAINTAINER Harald Welte <laforge@gnumonks.org>

RUN	apt-get update && apt-get install -y \
	build-essential \
	wget \
	git \
	make \
	autoconf \
	autogen \
	automake \
	libtool \
	pkg-config
