ARG	USER
FROM	$USER/debian-bullseye-obs-latest
# Arguments used after FROM must be specified again

RUN	apt-get update && \
	apt-get install -y --no-install-recommends \
		asciidoc \
		autoconf \
		autoconf-archive \
		autogen \
		automake \
		bison \
		build-essential \
		ca-certificates \
		dahdi-source \
		dblatex \
		git \
		graphviz \
		inkscape \
		libasn1c-dev \
		libboost-all-dev \
		libc-ares-dev \
		libcsv-dev \
		libdbd-sqlite3 \
		libdbi-dev \
		libfftw3-dev \
		libgnutls28-dev \
		libgps-dev \
		libgsm1-dev \
		libgtp-dev \
		libgtpnl-dev \
		liblimesuite-dev \
		libncurses5-dev \
		liboping-dev \
		liborcania-dev \
		libortp-dev \
		libosmo-abis-dev \
		libosmo-gsup-client-dev \
		libosmo-hnbap-dev \
		libosmo-mgcp-client-dev \
		libosmo-netif-dev \
		libosmo-ranap-dev \
		libnl-route-3-dev \
		libosmo-rua-dev \
		libosmo-sccp-dev \
		libosmo-sigtran-dev \
		libosmo-simtrace2-dev \
		libosmocore-dev \
		libosmodsp-dev \
		libpcap-dev \
		libpcsclite-dev \
		libreadline-dev \
		libsctp-dev \
		libsmpp34-dev \
		libsofia-sip-ua-glib-dev \
		libsqlite3-dev \
		libssl-dev \
		libtalloc-dev \
		libtool \
		libuhd-dev \
		libulfius-dev \
		libusb-1.0-0-dev \
		libusb-dev \
		libusrp-dev \
		libyder-dev \
		libzmq3-dev \
		make \
		mscgen \
		python3-nwdiag \
		xsltproc \
		&& \
	apt-get clean
