.PHONY: compile test log

all: compile test

compile:
	$(MAKE) -C /osmo-ttcn3-hacks msc/all

test:
	cd /data && \
		/osmo-ttcn3-hacks/start-testsuite.sh /osmo-ttcn3-hacks/msc/MSC_Tests MSC_Tests.cfg $(TEST); \
		exit_code=$$?; \
		/osmo-ttcn3-hacks/log_merge.sh MSC_Tests --rm; \
		exit $$exit_code
