.PHONY: compile test log

all: compile test

compile:
	$(MAKE) -C /osmo-ttcn3-hacks hlr/all

test:
	cd /data && \
		/osmo-ttcn3-hacks/start-testsuite.sh /osmo-ttcn3-hacks/hlr/HLR_Tests HLR_Tests.cfg $(TEST); \
		exit_code=$$?; \
		/osmo-ttcn3-hacks/log_merge.sh HLR_Tests --rm; \
		exit $$exit_code
