.PHONY: compile test log

default: compile test

compile:
	$(MAKE) -C /osmo-ttcn3-hacks smlc/compile
	$(MAKE) -C /osmo-ttcn3-hacks smlc -j

test:
	cd /data && \
		/osmo-ttcn3-hacks/start-testsuite.sh /osmo-ttcn3-hacks/smlc/SMLC_Tests; \
		exit_code=$$?; \
		/osmo-ttcn3-hacks/log_merge.sh SMLC_Tests --rm; \
		exit $$exit_code
