ARG	USER
FROM	$USER/debian-stretch-titan
ARG	OSMO_TTCN3_BRANCH="master"

ADD	http://git.osmocom.org/osmo-ttcn3-hacks/patch?h=$OSMO_TTCN3_BRANCH /tmp/commit
RUN	ttcn3-docker-prepare "$OSMO_TTCN3_BRANCH" bsc

VOLUME	/data

COPY	BSC_Tests.cfg /data/BSC_Tests.cfg

CMD	ttcn3-docker-run bsc BSC_Tests
