.PHONY: compile test log

default: compile test

compile:
	$(MAKE) -C /osmo-ttcn3-hacks bsc/compile
	$(MAKE) -C /osmo-ttcn3-hacks bsc -j

test:
	cd /data && \
		/osmo-ttcn3-hacks/start-testsuite.sh /osmo-ttcn3-hacks/bsc/BSC_Tests; \
		exit_code=$$?; \
		/osmo-ttcn3-hacks/log_merge.sh BSC_Tests --rm; \
		exit $$exit_code
